spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: "/h2-console"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
app:
  jwt:
    # Temporary secret for local testing
    secret: "68576D5A7134743777217A25432A462D4A614E645267556B586E3272357538782F413F4428472B4B6250655368566D5971337336763979244226452948404D63"
pimsprices:
  # Temporary values for local testing
  jwtExpirationS: 60000 # in miliseconds
  jwtRefreshExpirationS: 86400000 # in miliseconds

