apiVersion: v1
kind: Service
metadata:
  name: pims-prices-service
  annotations:
    cloud.google.com/backend-config: '{"default": "backend-config"}'
spec:
  type: LoadBalancer
  selector:
    app: pims-prices
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
