SET REFERENTIAL_INTEGRITY TRUE;

CREATE TABLE IF NOT EXISTS prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(255),
    price NUMERIC(38,2),
    currency VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS prices_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS prices_and_prices_categories (
    price_id BIGINT NOT NULL,
    prices_category_id BIGINT NOT NULL,
    PRIMARY KEY (price_id, prices_category_id),
    CONSTRAINT fk_price FOREIGN KEY (price_id) REFERENCES prices (id) ON DELETE CASCADE,
    CONSTRAINT fk_prices_categories FOREIGN KEY (prices_category_id) REFERENCES prices_categories (id) ON DELETE CASCADE
);

INSERT INTO prices (id, product_id, price, currency) VALUES
    (1, 'DE-098382', 19.99, 'EUR'),
    (2, 'PL-098382', 82.11, 'PLN');

INSERT INTO prices_categories (id, name) VALUES
    (1, 'Whole sale price'),
    (2, 'Retail price'),
    (3, 'Summer price'),
    (4, 'Winter price');


INSERT INTO prices_and_prices_categories (price_id, prices_category_id) VALUES
    (1, 2),
    (1, 3),
    (2, 1),
    (2, 3);

ALTER TABLE prices ALTER COLUMN id RESTART WITH 3;
ALTER TABLE prices_categories ALTER COLUMN id RESTART WITH 5;